name: StarTracer

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage nbconvert
        pip install .
    - name: Test with pytest
      run: pytest
    - name: Update readme
      run: jupyter nbconvert --template "pythoncodeblocks.tpl" --to markdown README.ipynb